name: lms

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  rxdart: ^0.27.7
  intl: ^0.19.0
  number_to_words_english: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  pretty_dio_logger: ^1.3.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf
